version: '2'

services:

  # nginx container
  nginx:
    build: ./docker/nginx/
    ports:
      - 8080:80
    volumes:
      - ./docroot:/var/www/html/
      - ./logs/nginx:/var/log/nginx/

  # mysql container
  mysql:
    build: ./docker/mysql/
    ports:
      - 3306
    environment:
    - MYSQL_ROOT_PASSWORD=root@mysqlserver
    volumes:
      - ./docker/mysql/mysql-data:/var/lib/mysql/
      - ./logs/mysql:/var/log/mysql/
    volumes_from:
      - php5-fpm

  # php-fpm container
  php5-fpm:
    build: ./docker/php5-fpm/
    ports:
      - 9000
    volumes:
      - ./docroot:/var/www/html/
      - ./docker/php5-fpm/configs:/usr/local/etc/php/
